In [1]:
import torch
torch.__version__

'2.0.1+cu117'

Criar tensor de 0 dimensão, ou seja Scalar

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# Quantidade de dimensões do tensor
scalar.ndim

0

In [4]:
# Retornar o item que está no tensor
scalar.item()

7

Um vetor é um tensor de uma única dimensão

In [5]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

Formato do tensor

In [6]:
vector.shape

torch.Size([2])

Matriz

In [7]:
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix.ndim
matrix.shape

torch.Size([2, 2])

Tensor

In [8]:
TENSOR = torch.tensor([[
                        [1, 2],
                        [3, 4],
                        [4, 5]
                    ]])

TENSOR

tensor([[[1, 2],
         [3, 4],
         [4, 5]]])

In [9]:
TENSOR.ndim

3

Criando tensores randômicos

In [10]:
random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.4810, 0.4197, 0.8361, 0.1363],
        [0.6205, 0.6718, 0.7641, 0.0031],
        [0.9043, 0.3204, 0.9624, 0.6841]])

Create ranges

In [11]:
range_0_to_10 = torch.arange(start=0, end=10, step=10)
range_0_to_10

tensor([0])