# Operações em Tensores

In [1]:
import torch

In [9]:
tensor = torch.arange(start=0, end=10, step=1)
tensor + 10

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
# Só altera o tensor original se for atribuído
tensor * 10
tensor
tensor = tensor * 10
tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

### Multiplicação de Matrizes
Utiliza o operador @

In [19]:
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [21]:
torch.matmul(tensor, tensor)
tensor @ tensor # mesma operação da linha anterior

tensor(14)

### Erro comum: multiplicação de matrizes com formatos diferentes

In [29]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [30]:
# Realizando transpose
output = tensor_A @ tensor_B.T # poderia usar torch.matmul(tensor_A, tensor_B.T)
print(output)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])


### Linear

In [44]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2, 
                        out_features=6)

x = tensor_A
output = linear(x)

print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])
