# Agregação: min, max, mean, sum, etc

In [1]:
import torch

In [9]:
x = torch.arange(start=0, end=100, step=10)
print(x)
print(f"Menor: ", x.min())
print(f"Maior: ", x.max())
print(f"Média: ", x.type(torch.float32).mean()) # won't work without float datatype
print(f"Soma: ", x.sum())

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Menor:  tensor(0)
Maior:  tensor(90)
Média:  tensor(45.)
Soma:  tensor(450)


### Change tensor type

In [34]:
x = torch.arange(0., 8., 1)
print(x)
x_stacked = torch.stack([x], dim=1) # try changing dim to dim=1 and see what happens
x_stacked

tensor([0., 1., 2., 3., 4., 5., 6., 7.])


tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.]])